import numpy as np

print("============= Zad 1 =================")
a = np.array([2,1,3])
b = np.array([1,1,2])
c = np.dot(a,b)
print(c)
print("============= Zad 2 =================")
a1 = np.arange(9).reshape((3,3))
b1 = np.arange(9).reshape((3,3))
print(a1.min(axis=1))
print(a1.min(axis=0))
print(b1.min(axis=1))
print(b1.min(axis=0))
print("============= Zad 3 =================")
A = np.array([[2,1,3]])
B = np.array([1,1,1])
C = np.matmul(A,B)
print(C)
print("============= Zad 4 =================")
a = np.ones(3, dtype='int32')
b = np.linspace(0,np.pi,3)
print(a*b)
print("============= Zad 5 =================")
